
name: Macos-clang PGO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: install opencv
      run: brew install opencv

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DENABLE_PGO=ON ..

    - name: Build
      run: |
        cd build
        make -j

    - name: Test
      run: ./build/high_bitrate_y4m --duration 100 --width 7680 --height 4320 --fps 120 --lines 100 > /dev/null

